:imagesdir: ../assets/images

== Introduction

The goal of this lab is to demonstrate the installation and configuration of Red Hat Lightspeed on a Red Hat Satellite server.
You will also register the RHEL hosts to the Satellite server and verify that the hosts are being monitored by the Red Hat Lightspeed services.

== Lab Environment

The lab environment consists of the following

- Red Hat Satellite Server (Satellite is preinstalled and content/software is synchronized.)
- Two Red Hat Enterprise Linux hosts, *rhel1.lab* and *rhel2.lab*.

image::module-01-lab-environment.svg[Lab Environment Diagram,width=700,align="center"]

The Satellite server (*satellite.lab*) is preinstalled and manages both RHEL hosts,
handling content synchronization, registration, and subscriptions.

Over the course of this lab, you will:

. Install Red Hat Lightspeed on the Satellite server.
. Download the latest cvemap.xml vulnerability database.
. Verify the RHEL hosts are being monitored by the Red Hat Lightspeed services.

image::module-01-lab-environment-v2.svg[Lab Environment Diagram,width=700,align="center"]

== Log into the Web UI

First, we'll log into the Red Hat Satellite Web User Interface (UI).
Satellite has been preinstalled and installation is out of scope for
this lab.

Click on the tab labelled Satellite Web UI as shown in the image below.

You'll need the following credentials to log into the Satellite Web UI.

You can copy and paste each of them below.

[source,js]
----
admin
----

[source,js]
----
bc31c9a6-9ff0-11ec-9587-00155d1b0702
----

Now click `+Log In+`.

You will be taken to the main dashboard.
